import type {
  User,
  Enfunde,
  Cosecha,
  Empleado,
  RolPago,
  Prestamo,
  Insumo,
  MovimientoInventario,
  Alerta,
  RecuperacionCinta,
  Finca,
  FincaName,
} from "./types"

export const mockFincas: Finca[] = [
  {
    id: "1",
    nombre: "BABY",
    hectareas: 45.5,
    ubicacion: "Km 26 vía Machala - Pasaje",
    responsable: "Juan Pérez",
    variedad: "Cavendish",
    plantasTotales: 50000,
  },
  {
    id: "2",
    nombre: "SOLO",
    hectareas: 38.2,
    ubicacion: "Km 28 vía Machala - Pasaje",
    responsable: "María González",
    variedad: "Cavendish",
    plantasTotales: 42000,
  },
  {
    id: "3",
    nombre: "LAURITA",
    hectareas: 52.8,
    ubicacion: "Km 30 vía Machala - Pasaje",
    responsable: "Carlos Hernández",
    variedad: "Cavendish",
    plantasTotales: 58000,
  },
  {
    id: "4",
    nombre: "MARAVILLA",
    hectareas: 61.3,
    ubicacion: "Km 32 vía Machala - Pasaje",
    responsable: "Ana Torres",
    variedad: "Cavendish",
    plantasTotales: 67000,
  },
]

export const mockUsers: User[] = [
  {
    id: "1",
    nombre: "Carlos Hernández",
    email: "admin@bananerahg.com",
    password: "admin123",
    rol: "administrador",
    telefono: "0987654321",
    activo: true,
    avatar: "/admin-interface.png",
  },
  {
    id: "2",
    nombre: "María González",
    email: "gerente@bananerahg.com",
    password: "gerente123",
    rol: "gerente",
    telefono: "0976543210",
    activo: true,
    avatar: "/diverse-team-manager.png",
  },
  {
    id: "3",
    nombre: "Juan Pérez",
    email: "supervisor@bananerahg.com",
    password: "supervisor123",
    rol: "supervisor",
    fincaAsignada: "1",
    telefono: "0965432109",
    activo: true,
    avatar: "/supervisor.png",
  },
  {
    id: "4",
    nombre: "Ana Torres",
    email: "operador@bananerahg.com",
    password: "operador123",
    rol: "operador",
    fincaAsignada: "2",
    telefono: "0954321098",
    activo: true,
  },
  {
    id: "5",
    nombre: "Luis Mendoza",
    email: "consulta@bananerahg.com",
    password: "consulta123",
    rol: "consulta",
    telefono: "0943210987",
    activo: true,
  },
]

export const mockEnfundes: Enfunde[] = [
  {
    id: "1",
    finca: "BABY",
    semana: 1,
    año: 2025,
    colorCinta: "Azul",
    cantidadEnfundes: 1250,
    matasCaidas: 15,
    fecha: "2025-01-06",
  },
  {
    id: "2",
    finca: "SOLO",
    semana: 1,
    año: 2025,
    colorCinta: "Rojo",
    cantidadEnfundes: 980,
    matasCaidas: 8,
    fecha: "2025-01-06",
  },
  {
    id: "3",
    finca: "LAURITA",
    semana: 1,
    año: 2025,
    colorCinta: "Verde",
    cantidadEnfundes: 1100,
    matasCaidas: 12,
    fecha: "2025-01-06",
  },
  {
    id: "4",
    finca: "MARAVILLA",
    semana: 1,
    año: 2025,
    colorCinta: "Amarillo",
    cantidadEnfundes: 1350,
    matasCaidas: 10,
    fecha: "2025-01-06",
  },
]

export const mockCosechas: Cosecha[] = [
  {
    id: "1",
    finca: "BABY",
    semana: 1,
    año: 2025,
    racimosCorta: 1200,
    racimosRechazados: 45,
    racimosRecuperados: 1155,
    cajasProducidas: 2540,
    pesoPromedio: 42.5,
    calibracion: 46,
    numeroManos: 9.2,
    ratio: 2.2,
    merma: 3.75,
  },
  {
    id: "2",
    finca: "SOLO",
    semana: 1,
    año: 2025,
    racimosCorta: 950,
    racimosRechazados: 32,
    racimosRecuperados: 918,
    cajasProducidas: 1980,
    pesoPromedio: 41.8,
    calibracion: 45,
    numeroManos: 8.9,
    ratio: 2.16,
    merma: 3.37,
  },
  {
    id: "3",
    finca: "LAURITA",
    semana: 1,
    año: 2025,
    racimosCorta: 1080,
    racimosRechazados: 38,
    racimosRecuperados: 1042,
    cajasProducidas: 2250,
    pesoPromedio: 43.2,
    calibracion: 47,
    numeroManos: 9.5,
    ratio: 2.16,
    merma: 3.52,
  },
  {
    id: "4",
    finca: "MARAVILLA",
    semana: 1,
    año: 2025,
    racimosCorta: 1320,
    racimosRechazados: 48,
    racimosRecuperados: 1272,
    cajasProducidas: 2800,
    pesoPromedio: 44.1,
    calibracion: 48,
    numeroManos: 9.8,
    ratio: 2.2,
    merma: 3.64,
  },
]

export const mockEmpleados: Empleado[] = [
  {
    id: "1",
    nombre: "Pedro Ramírez",
    cedula: "0912345678",
    finca: "BABY",
    labor: "Enfunde",
    lote: "A-12",
    tarifaDiaria: 18.5,
    fechaIngreso: "2023-03-15",
    cuentaBancaria: "1234567890",
    telefono: "0987654321",
    direccion: "Guayaquil, Ecuador",
    activo: true,
  },
  {
    id: "2",
    nombre: "Luis Mendoza",
    cedula: "0923456789",
    finca: "BABY",
    labor: "Cosecha",
    lote: "A-15",
    tarifaDiaria: 20.0,
    fechaIngreso: "2022-08-20",
    cuentaBancaria: "2345678901",
    telefono: "0976543210",
    direccion: "Machala, Ecuador",
    activo: true,
  },
  {
    id: "3",
    nombre: "Ana Torres",
    cedula: "0934567890",
    finca: "SOLO",
    labor: "Calibración",
    lote: "B-08",
    tarifaDiaria: 19.0,
    fechaIngreso: "2023-01-10",
    cuentaBancaria: "3456789012",
    telefono: "0965432109",
    direccion: "El Oro, Ecuador",
    activo: true,
  },
  {
    id: "4",
    nombre: "Roberto Silva",
    cedula: "0945678901",
    finca: "LAURITA",
    labor: "Varios",
    lote: "C-20",
    tarifaDiaria: 17.5,
    fechaIngreso: "2024-02-01",
    cuentaBancaria: "4567890123",
    telefono: "0954321098",
    direccion: "Pasaje, Ecuador",
    activo: true,
  },
  {
    id: "5",
    nombre: "Carmen Vega",
    cedula: "0956789012",
    finca: "MARAVILLA",
    labor: "Administrador",
    tarifaDiaria: 25.0,
    fechaIngreso: "2021-05-15",
    cuentaBancaria: "5678901234",
    telefono: "0943210987",
    direccion: "Machala, Ecuador",
    activo: true,
  },
]

export const mockRolesPago: RolPago[] = [
  {
    id: "1",
    empleadoId: "1",
    empleado: mockEmpleados[0],
    finca: "BABY",
    semana: 1,
    año: 2025,
    diasLaborados: 6,
    horasExtras: 4,
    sueldoBase: 111.0,
    cosecha: 45.0,
    tareasEspeciales: 30.0,
    totalIngresos: 186.0,
    iess: 9.52,
    multas: 0,
    prestamos: 20.0,
    totalEgresos: 29.52,
    netoAPagar: 156.48,
    estado: "pendiente",
  },
  {
    id: "2",
    empleadoId: "2",
    empleado: mockEmpleados[1],
    finca: "BABY",
    semana: 1,
    año: 2025,
    diasLaborados: 6,
    horasExtras: 2,
    sueldoBase: 120.0,
    cosecha: 80.0,
    tareasEspeciales: 25.0,
    totalIngresos: 225.0,
    iess: 11.52,
    multas: 0,
    prestamos: 0,
    totalEgresos: 11.52,
    netoAPagar: 213.48,
    estado: "pagado",
  },
]

export const mockPrestamos: Prestamo[] = [
  {
    id: "1",
    empleadoId: "1",
    empleado: mockEmpleados[0],
    monto: 500.0,
    fechaDesembolso: "2024-12-01",
    numeroCuotas: 25,
    valorCuota: 20.0,
    cuotasPagadas: 5,
    saldoPendiente: 400.0,
    estado: "activo",
  },
  {
    id: "2",
    empleadoId: "3",
    empleado: mockEmpleados[2],
    monto: 300.0,
    fechaDesembolso: "2024-11-15",
    numeroCuotas: 15,
    valorCuota: 20.0,
    cuotasPagadas: 8,
    saldoPendiente: 140.0,
    estado: "activo",
  },
]

export const mockInsumos: Insumo[] = [
  {
    id: "1",
    nombre: "Fertilizante NPK 15-15-15",
    categoria: "fertilizante",
    proveedor: "AgroQuímicos SA",
    unidadMedida: "kg",
    stockActual: 450,
    stockMinimo: 200,
    stockMaximo: 1000,
    precioUnitario: 1.25,
    fechaVencimiento: "2025-12-31",
  },
  {
    id: "2",
    nombre: "Protector de racimo",
    categoria: "protector",
    proveedor: "Plásticos del Banano",
    unidadMedida: "unidad",
    stockActual: 8500,
    stockMinimo: 5000,
    stockMaximo: 15000,
    precioUnitario: 0.15,
  },
  {
    id: "3",
    nombre: "Cinta de colores",
    categoria: "empaque",
    proveedor: "Empaques HG",
    unidadMedida: "rollo",
    stockActual: 120,
    stockMinimo: 80,
    stockMaximo: 300,
    precioUnitario: 8.5,
  },
  {
    id: "4",
    nombre: "Fungicida Mancozeb",
    categoria: "protector",
    proveedor: "AgroQuímicos SA",
    unidadMedida: "litro",
    stockActual: 45,
    stockMinimo: 100,
    stockMaximo: 300,
    precioUnitario: 12.8,
    fechaVencimiento: "2025-06-30",
  },
]

export const mockMovimientosInventario: MovimientoInventario[] = [
  {
    id: "1",
    insumoId: "1",
    tipo: "entrada",
    cantidad: 500,
    fecha: "2025-01-02",
    motivo: "Compra mensual",
    responsable: "Carmen Vega",
  },
  {
    id: "2",
    insumoId: "1",
    tipo: "salida",
    cantidad: 50,
    fecha: "2025-01-05",
    motivo: "Aplicación Finca BABY",
    responsable: "Juan Pérez",
  },
  {
    id: "3",
    insumoId: "2",
    tipo: "salida",
    cantidad: 1500,
    fecha: "2025-01-06",
    motivo: "Enfunde semana 1",
    responsable: "Pedro Ramírez",
  },
]

export const mockAlertas: Alerta[] = [
  {
    id: "1",
    tipo: "critico",
    modulo: "Inventario",
    titulo: "Stock crítico: Fungicida Mancozeb",
    descripcion: "El stock actual (45 L) está por debajo del mínimo requerido (100 L)",
    fecha: "2025-01-06T08:30:00",
    leida: false,
    accionRequerida: "Realizar pedido urgente",
  },
  {
    id: "2",
    tipo: "advertencia",
    modulo: "Producción",
    titulo: "Recuperación baja en Finca SOLO",
    descripcion: "La recuperación de cintas en semana 52 fue del 78%, por debajo del 80% esperado",
    fecha: "2025-01-05T14:20:00",
    leida: false,
  },
  {
    id: "3",
    tipo: "info",
    modulo: "Nómina",
    titulo: "Roles de pago listos",
    descripcion: "Los roles de pago de la semana 1 están listos para revisión",
    fecha: "2025-01-06T10:00:00",
    leida: true,
  },
  {
    id: "4",
    tipo: "advertencia",
    modulo: "Producción",
    titulo: "Merma elevada en MARAVILLA",
    descripcion: "La merma de la semana 1 (3.64%) supera el promedio histórico (3.2%)",
    fecha: "2025-01-06T16:45:00",
    leida: false,
  },
]

export const mockRecuperacionCintas: RecuperacionCinta[] = [
  {
    id: "1",
    finca: "BABY",
    semana: 52,
    año: 2024,
    enfundesIniciales: 1250,
    primeraCalCosecha: 450,
    primeraCalSaldo: 800,
    segundaCalCosecha: 520,
    segundaCalSaldo: 280,
    terceraCalCosecha: 185,
    terceraCalSaldo: 95,
    barridaFinal: 45,
    porcentajeRecuperacion: 96.0,
  },
  {
    id: "2",
    finca: "SOLO",
    semana: 52,
    año: 2024,
    enfundesIniciales: 980,
    primeraCalCosecha: 350,
    primeraCalSaldo: 630,
    segundaCalCosecha: 410,
    segundaCalSaldo: 220,
    terceraCalCosecha: 145,
    terceraCalSaldo: 75,
    barridaFinal: 20,
    porcentajeRecuperacion: 78.0,
  },
]

// Helper functions
export function getEnfundesByFinca(finca: FincaName): Enfunde[] {
  return mockEnfundes.filter((e) => e.finca === finca)
}

export function getCosechasByFinca(finca: FincaName): Cosecha[] {
  return mockCosechas.filter((c) => c.finca === finca)
}

export function getEmpleadosByFinca(finca: FincaName): Empleado[] {
  return mockEmpleados.filter((e) => e.finca === finca)
}

export function getTotalProduccionSemanal(): number {
  return mockCosechas.reduce((sum, c) => sum + c.cajasProducidas, 0)
}

export function getAlertasNoLeidas(): Alerta[] {
  return mockAlertas.filter((a) => !a.leida)
}

export function getInsumosStockBajo(): Insumo[] {
  return mockInsumos.filter((i) => i.stockActual < i.stockMinimo)
}
