# Generated by Django 5.1.2 on 2026-01-18 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bananera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='proveedor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='insumo',
            name='stock_maximo',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='categoria',
            field=models.CharField(choices=[('fertilizante', 'Fertilizante'), ('protector', 'Protector'), ('herramienta', 'Herramienta'), ('empaque', 'Empaque'), ('quimico', 'Químico'), ('par', 'Par'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='finca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='bananera.finca'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo'), ('litro', 'Litro'), ('metro', 'Metro'), ('rollo', 'Rollo'), ('caja', 'Caja'), ('par', 'Par')], default='unidad', max_length=20),
        ),
    ]
